### ISSUE TITLE
Needs Disqus

### ISSUE THREAD

**Issue by brenns10** [ajm188/ajm188.github.io#1]
How am I supposed to comment on your posts without Disqus??

**Comment by ajm188** [comment]
Fair point. I'll try to get this set up later today. Then you can comment until your heart's content.

**Comment by brenns10** [comment]
It looks like since you're doing Jekyll now, you just sign up for Disqus, and then edit your Disqus site name into your `_config.yml`.

**Comment by ajm188** [comment]
Cool. :+1: for saving me from an unknowable amount of time googling.
